export const GET_ALL_DOGS = "GET_ALL_DOGS";
export const GET_DOGS_BY_NAME = "GET_DOGS_BY_NAME";
export const GET_ALL_TEMPERAMENTS = "GET_ALL_TEMPERAMENTS";
export const FILTER_BY_TEMPERAMENT = "FILTER_BY_TEMPERAMENT";
export const GET_ALL_DOGS_ONLY_API = "GET_ALL_DOGS_ONLY_API";
export const GET_ALL_DOGS_ONLY_BDD = "GET_ALL_DOGS_ONLY_BDD";
export const DETAIL_ID_RAZA = "DETAIL_ID_RAZA";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
